# Generated by Django 5.2.7 on 2025-11-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_login_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='approach',
            new_name='approaved',
        ),
    ]
